use_frameworks!

platform :ios, '8.0'

## pod update --verbose --no-repo-update
## pod install --verbose --no-repo-update

target 'RACDemo' do
    pod 'AFNetworking'
    pod 'ReactiveCocoa', '~> 2.5'
    pod 'Masonry'
    pod 'MJRefresh', '~> 3.1.12'
    pod 'Reachability', '~> 3.2'
    pod 'MJExtension', '~> 3.0.13'

end
